# "Work in Progress: Recreating Fast.ai Chapter 5 Using TensorFlow/Keras"
> "To test my understanding of the [Fast.ai course](https://course.fast.ai/) and to improve my TensorFlow/Keras skills, I am reimplementing chapters of the FastBook in TF/Keras. Note, this is post is a **work in progress**, and will be updated as I work on it. Started: 7/21/21. Last updated: 7/22/21."

- toc: true
- categories: [fastai, tensorflow, keras]

# Image Classification

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pathlib import Path
import re

## From Dogs and Cats to Pet Breeds

In [4]:
path = Path("/home/brandon/.fastai/data/oxford-iiit-pet/images/")

In [5]:
len(list(path.iterdir()))

7393

In [6]:
data = tf.data.Dataset.list_files(str(path/"*.jpg"), shuffle=True, seed=42);data

<ShuffleDataset shapes: (), types: tf.string>

In [8]:
list(iter(data))[:5]

[<tf.Tensor: shape=(), dtype=string, numpy=b'/home/brandon/.fastai/data/oxford-iiit-pet/images/Russian_Blue_67.jpg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'/home/brandon/.fastai/data/oxford-iiit-pet/images/boxer_28.jpg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'/home/brandon/.fastai/data/oxford-iiit-pet/images/wheaten_terrier_27.jpg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'/home/brandon/.fastai/data/oxford-iiit-pet/images/miniature_pinscher_171.jpg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'/home/brandon/.fastai/data/oxford-iiit-pet/images/beagle_39.jpg'>]

In [17]:
class_names = {re.findall("^(.+)_\d+$", f.stem)[0] for f in path.glob("*.jpg")}; len(class_names)

37

In [24]:
class_names = np.array(sorted(class_names)); class_names

array(['Abyssinian', 'Bengal', 'Birman', 'Bombay', 'British_Shorthair',
       'Egyptian_Mau', 'Maine_Coon', 'Persian', 'Ragdoll', 'Russian_Blue',
       'Siamese', 'Sphynx', 'american_bulldog',
       'american_pit_bull_terrier', 'basset_hound', 'beagle', 'boxer',
       'chihuahua', 'english_cocker_spaniel', 'english_setter',
       'german_shorthaired', 'great_pyrenees', 'havanese',
       'japanese_chin', 'keeshond', 'leonberger', 'miniature_pinscher',
       'newfoundland', 'pomeranian', 'pug', 'saint_bernard', 'samoyed',
       'scottish_terrier', 'shiba_inu', 'staffordshire_bull_terrier',
       'wheaten_terrier', 'yorkshire_terrier'], dtype='<U26')

In [ ]:
def get_x_and_y(file):
    """Gets independent and dependent variables."""
    return file, re.findall(r"/(.+)_\d+.jpg")

In [ ]:
tf.strings.regex_full_match()

## Presizing

### Checking and Debugging a DataBlock

## Cross-Entropy Loss

### Viewing Activations and Labels

### Softmax

### Log Likelihood

### Taking the Log

## Model Interpretation

## Improving Our Model

### The Learning Rate Finder

### Unfreezing and Transfer Learning

### Discriminative Learning Rates

### Selecting the Number of Epochs

### Deeper Architectures